### ISSUE TITLE
Why delay releases via pre-releases if GISAID does not apply newest release for a few days-weeks anyways?

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pangolin-data#27]
I've noticed that you seem to delay the full release of pangolin-data, doing a pre-release first, with the argument being that this allows GISAID to be able to update their lineages ahead of the release.

I've just checked and GISAID is not using the newest version v1.15.1 for the very newest uploads despite the prerelease having occurred a few days ago.

Here you can see that v1.14 is still used (I remember that v1.14 started being used only weeks after the official release by GISAID, despite pre-release):
<img width="671" alt="image" src="https://user-images.githubusercontent.com/25161793/195066382-efacbe29-33f1-45b7-9ce6-48f5f3af12f1.png">

So the argument of allowing GISAID a few days to sync appears not to be very convincing, at least at the moment.

I'm wondering whether this delay is more harmful than beneficial as it further delays the appearance of new important lineages like BQ.1.1, XBB etc. for pangolin users who do not use GISAID's annotation but run pangolin directly.

**Comment by corneliusroemer** [comment]
Here's the reasoning for the delay:

> We haven't tagged a new pangolin data release yet, the latest one is still 1.14. Will tag it later today, just giving GISAID the time to update prior to tagging the release

_Originally posted by @aineniamh in https://github.com/cov-lineages/pango-designation/issues/1199#issuecomment-1273392408_

**Comment by aineniamh** [comment]
We no longer do a pre-release but we now merge to master ~12 hours before tagging the release. This was the agreement we had with them to give some heads up for starting the re-assignment process. It's no big deal on our end to wait 12 hours if it's something that is helpful to GISAID.

Maybe contact them if you think it's worth revising that schedule?

**Comment by corneliusroemer** [comment]
Thanks @aineniamh, I wasn't aware this was just 12 hours, in that case it isn't worth discussing. Thanks for clarifying!
