### ISSUE TITLE
BQ.1.13.1 assigned but not annotated in the json file (or online)

### ISSUE THREAD

**Issue by AKWB** [cov-lineages/pangolin-data#34]
Hi there,

I just ran an analysis and came across a case of BQ.1.13.1. This lineage is not to find in the annotation-json file.

Greets

**Comment by AKWB** [comment]
I will place this request in the webpage part...I guess its better placed there

**Comment by aineniamh** [comment]
This lineage was only added after the last pangolin-data release (https://github.com/cov-lineages/pango-designation/blame/04cb7e2da40144f0ad33510a0addb2290dfffc6e/lineage_notes.txt#L2395) so has not been incorporated into the latest model yet, so hasn't appeared on the website. The next pangolin-data release should include this lineage.

**Comment by AKWB** [comment]
But, why does my rerun of pangolin then assign this lineage already? Or its due to the fact that I made a complete reinstall of pangolin due to the usher version, and by this I caught the newest, intermediate - not yet released - data version. I will add this lineage description then manually in my annotation file, for the time being.

Tahnks!!!

**Comment by AngieHinrichs** [comment]
Actually XBB.1.9 just barely squeaked into pango-designation [v1.18](https://github.com/cov-lineages/pango-designation/releases/tag/v1.18) (designated 2023-01-08, v1.18 tagged on 2023-01-09).  BQ.1.13.1 was designated on 2022-12-25: https://github.com/cov-lineages/pango-designation/blame/04cb7e2da40144f0ad33510a0addb2290dfffc6e/lineage_notes.txt#L1251 .  So both were included in pangolin-data release [v1.18](https://github.com/cov-lineages/pangolin-data/releases/tag/v1.18) on 2023-01-18. 

@AKWB when you say "the annotation-json file" which file are you referring to?

**Comment by AngieHinrichs** [comment]
The lineages website was updated [yesterday](https://github.com/cov-lineages/lineages-website/commit/40b3a79e00edbde30867961f5493884b7da31afe) so the data you're looking for are probably there now.
