### ISSUE TITLE
Alias XDS missing

### ISSUE THREAD

**Issue by WhalleyT** [cov-lineages/pangolin-data#52]
Hi,

I noticed when running pangolin that the alias keys don't seem to be updated from 1.24 -> 1.25.  When running pangolin I get the error

```
generate_final_report(preprocessing_csv, inference_csv, cached_csv, config[KEY_ALIAS_FILE], constellation_list, config[KEY_PANGOLIN_DATA_VERSION],config[KEY_ANALYSIS_MODE], args.skip_designation_cache, config[KEY_OUTFILE],config)
  File "/lib/python3.8/site-packages/pangolin/utils/report_collation.py", line 234, in generate_final_report
    recombinant_parents = get_recombinant_parents(expanded_pango_lineage, alias_dict)
  File "/lib/python3.8/site-packages/pangolin/utils/report_collation.py", line 94, in get_recombinant_parents
    for parent in alias_dict[lineage_parts[0]]:
KeyError: 'XDS
```

and I see that in ```pangolin_data/data/alias_key.json``` XDS is not there in spite of having been added into [pango-designation](https://github.com/cov-lineages/pango-designation) and it looks like the json is still at 1.24 where the remaining files are at 1.25. Sorry if I'm getting the wrong end of the stick or the files are still in the process of being bumped up!

Thanks, Tom

**Comment by AngieHinrichs** [comment]
No, you're right Tom!  I accidentally checked out the wrong version of pango-designation when copying in that file.  Fixed so it won't happen that way in the future.  Stand by for a v1.25.1, sorry about that.

**Comment by AngieHinrichs** [comment]
[pangolin-data v1.25.1](https://github.com/cov-lineages/pangolin-data/releases/tag/v1.25.1) is out now.  Thanks so much for reporting this @WhalleyT!

**Comment by WhalleyT** [comment]
That's great! Thanks for the speedy update 🙂
